version: '3'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/source:/django
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    
  db:
    container_name: db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./docker/mysql/data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_USER: pengin
      MYSQL_PASSWORD: pengin
